export const environment = {
 production: false,
 backendApiUrl: "http://localhost:8081/api",
 defaultShippingAddressStreetMinLength: 3,
 defaultFirstNameMinLength: 2,
 defaultProductNameMinLength: 2,
 bugTextButtonLogout: "Logout",
 bugTextButtonMembers: "Members",
 bugTextButtonOrders: "Orders",
 bugTextButtonSearch: "Search",
 bugEditCategoryRoute: '/edit/category',
 bugAddCategoryRoute: '/add/category',
 bugDeleteCategoryRoute: '/delete/category',
 bugShippingAddressStreetMinLength: 2,
 bugFirstNameMinLength: 2,
 bugProductNameMinLength: 2,
 bugCardNumberLength: 16,
 bugSecurityCodeLength: 3,
 bugCategoryNameRequired: true,
 bugReplaceProductInCart: false,
}
