export const environment = {
 production: false,
 backendApiUrl: "http://localhost:8081/api",
 bugTextButtonLogout: "Logout",
 bugTextButtonMembers: "Members",
 bugTextButtonOrders: "Orders",
 bugTextButtonSearch: "Search",
 bugEditCategoryRoute: '/edit/category',
 bugAddCategoryRoute: '/add/category',
 bugDeleteCategoryRoute: '/delete/category',
 bugShippingAddressStreetMinLength: 3,
 bugFirstNameMinLength: 4,
 bugProductNameMinLength: 5,
 bugCardNumberLength: 10,
 bugSecurityCodeLength: 3,
 bugCategoryNameRequired: false,
}
